# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15WSaURI70MKpV97GslvTOQULO3aQ8Ff5
"""

a=int(input("numero a: "))
b=int(input("numero b: "))
if a>b:
  print("a es mayor que b")
elif a<b:
  print("a es menor que b")
elif a==b:
  print("a es igual a b")

nota1= 2.3*0.3
nota2 =3.5

Y=int(input("numero a: "))
Z=int(input("numero b: "))
if Y>Z:
  x=1
elif Y==Z:
  x=2
elif Y<Z:
  x=3